// ******************************************************************************************************
// DO NOT DELETE!
// This index.js is required to render cucumber feature test steps generated by the mochawesome-reporter.
// ******************************************************************************************************
import 'cypress-mochawesome-reporter/cucumberSupport';
